services:
  - type: web
    name: weharate
    env: docker
    plan: free
    branch: main
    region: Singapore
    dockerfilePath: Dockerfile
    dockerContext: .
    autoDeploy: true
    envVars:
      - key: VITE_API_URL
        value: https://weharatebe.onrender.com
      - key: VITE_WS_URL
        value: wss://weharatebe.onrender.com/ws
