services:
  - type: web
    name: chat-app-frontend
    env: docker
    plan: free
    branch: main
    dockerfilePath: Dockerfile
    dockerContext: .
    autoDeploy: true
    envVars:
      - key: VITE_API_URL
        value: https://chat-app-backend-pg6c.onrender.com
      - key: VITE_WS_URL
        value: wss://chat-app-backend-pg6c.onrender.com/ws