services:
  - type: web
    name: chat-app-frontend
    env: docker
    plan: free
    branch: main
    dockerfilePath: Dockerfile
    dockerContext: .
    autoDeploy: true
    envVars:
      - key: REACT_APP_API_URL
        value: https://fastapi-backend.onrender.com
